### ISSUE TITLE
Keys with dots as delimiters

### ISSUE THREAD

**Issue by Alvant** [spairet/nip#9]
Currently, NIP can not parse configs like this:
```yml
layer1.0.conv1.weight:
  distr_name: normal
  distr_params:
    mean: 0.0
    std: 1.0
```

This is because of the key `layer1.0.conv1.weight`
